name: Deploy Website
on: [push]
jobs:
  build:
    name: Build Docker File
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: sudo docker build -t trpg .
  deploy:
    name: Deploy Docker Container
    runs-on: [self-hosted, linux]
    needs: [build]
    steps:
      - run: sudo docker-compose up -d
  prune:
    name: Prune Unused Image
    runs-on: [self-hosted, linux]
    needs: [deploy]
    steps:
      - run: sudo docker prune


