name: Deploy Website
on: [push]
env:
  BASE_DIR: /home/itiscaleb
jobs:
  build:
    name: Build Docker File
    runs-on: [self-hosted, linux]
    steps:
      - run: sudo chown -R $USER:$USER /home/itiscaleb/actions-runner/_work/TRPG-Character-Sheet
      - uses: actions/checkout@v2
      - run: sudo docker build -t trpg .
  deploy:
    name: Deploy Docker Container
    runs-on: [self-hosted, linux]
    needs: [build]
    steps:
      - run: ln -s $BASE_DIR/TRPG-Character-Sheet/.env
      - run: ln -s $BASE_DIR/TRPG-Character-Sheet/mongo
      - run: sudo docker-compose up -d
  prune:
    name: Prune Unused Image
    runs-on: [self-hosted, linux]
    needs: [deploy]
    steps:
      - run: sudo docker image prune -f


